
from pathlib import Path

code = []
code.append("import re, shutil, py_compile")
code.append("from datetime import datetime")
code.append("from pathlib import Path")
code.append("")
code.append("TIMESTAMP = datetime.now().strftime(\"%Y%m%d_%H%M%S\")")
code.append("ARCHIVE = Path(\"archive/fx6_\" + TIMESTAMP)")
code.append("ARCHIVE.mkdir(parents=True, exist_ok=True)")
code.append("results = []")
code.append("")
code.append("def backup(path):")
code.append("    src = Path(path)")
code.append("    if src.exists():")
code.append("        dst = ARCHIVE / Path(path)")
code.append("        dst.parent.mkdir(parents=True, exist_ok=True)")
code.append("        shutil.copy2(src, dst)")
code.append("")
code.append("# FX6-1: OrderBlock regime 파라미터 추가")
code.append("p1 = Path(\"strategies/v2/order_block_v2.py\")")
code.append("if p1.exists():")
code.append("    backup(\"strategies/v2/order_block_v2.py\")")
code.append("    s1 = p1.read_text(encoding=\"utf-8\")")
code.append("    old1 = \"def generate_signal(self, df: pd.DataFrame, market: str = \\\"\\\") -> Optional[Signal]:\"")
code.append("    new1 = \"def generate_signal(self, df: pd.DataFrame, market: str = \\\"\\\", regime: str = \\\"\\\") -> Optional[Signal]:\"")
code.append("    if old1 in s1:")
code.append("        p1.write_text(s1.replace(old1, new1), encoding=\"utf-8\")")
code.append("        results.append(\"OK   FX6-1: OrderBlock regime 파라미터\")")
code.append("    else:")
code.append("        results.append(\"SKIP FX6-1: 패턴 없음 (시그니처 확인 필요)\")")
code.append("else:")
code.append("    results.append(\"SKIP FX6-1: 파일 없음\")")
code.append("")
code.append("# FX6-2: PPO shape mismatch 방어")
code.append("p2 = Path(\"models/rl/ppo_agent.py\")")
code.append("if p2.exists():")
code.append("    backup(\"models/rl/ppo_agent.py\")")
code.append("    s2 = p2.read_text(encoding=\"utf-8\")")
code.append("    old2 = \"        try:\\n            action, _states = self._model.predict(\"")
code.append("    guard = (")
code.append("        \"        # [FX6-2] shape mismatch 방어\\n\"")
code.append("        \"        if self._model is not None:\\n\"")
code.append("        \"            _exp = self._model.observation_space.shape[0]\\n\"")
code.append("        \"            _act = int(state.reshape(-1).shape[0])\\n\"")
code.append("        \"            if _act != _exp:\\n\"")
code.append("        \"                logger.debug(\\\"PPO shape %d != %d skip\\\", _act, _exp)\\n\"")
code.append("        \"                return None, 0.0\\n\"")
code.append("    )")
code.append("    if \"[FX6-2]\" in s2:")
code.append("        results.append(\"SKIP FX6-2: 이미 적용\")")
code.append("    elif old2 in s2:")
code.append("        p2.write_text(s2.replace(old2, guard + old2), encoding=\"utf-8\")")
code.append("        results.append(\"OK   FX6-2: PPO shape guard\")")
code.append("    else:")
code.append("        results.append(\"SKIP FX6-2: 위치 없음\")")
code.append("else:")
code.append("    results.append(\"SKIP FX6-2: 파일 없음\")")
code.append("")
code.append("# FX6-3: profit_rate /100 수정 (engine_sell.py)")
code.append("p3 = Path(\"core/engine_sell.py\")")
code.append("if p3.exists():")
code.append("    backup(\"core/engine_sell.py\")")
code.append("    s3 = p3.read_text(encoding=\"utf-8\")")
code.append("    old3a = \"                \\\"profit_rate\\\": profit_rate,\\n                \\\"strategy\\\":    _strat,\"")
code.append("    new3a = \"                \\\"profit_rate\\\": profit_rate / 100.0,  # [FX6-3]\\n                \\\"strategy\\\":    _strat,\"")
code.append("    old3b = \"                \\\"profit_rate\\\": profit_rate,\\n                \\\"strategy\\\":    _strat_name,\"")
code.append("    new3b = \"                \\\"profit_rate\\\": profit_rate / 100.0,  # [FX6-3]\\n                \\\"strategy\\\":    _strat_name,\"")
code.append("    n3a = s3.count(old3a)")
code.append("    n3b = s3.count(old3b)")
code.append("    s3 = s3.replace(old3a, new3a, 1).replace(old3b, new3b, 1)")
code.append("    p3.write_text(s3, encoding=\"utf-8\")")
code.append("    results.append(\"OK   FX6-3: profit_rate /100 partial=\" + str(n3a) + \" sell=\" + str(n3b))")
code.append("else:")
code.append("    results.append(\"SKIP FX6-3: 파일 없음\")")
code.append("")
code.append("# FX6-5: 익절 후 30분 쿨다운 (engine_sell.py)")
code.append("p5 = Path(\"core/engine_sell.py\")")
code.append("if p5.exists():")
code.append("    s5 = p5.read_text(encoding=\"utf-8\")")
code.append("    cd = (")
code.append("        \"\\n        # [FX6-5] 익절 후 30분 재진입 쿨다운\\n\"")
code.append("        \"        if profit_rate > 0 and not _is_sl:\\n\"")
code.append("        \"            if not hasattr(self, \\\"_sl_cooldown\\\"):\\n\"")
code.append("        \"                self._sl_cooldown = {}\\n\"")
code.append("        \"            self._sl_cooldown[market] = _dt.datetime.now() + _dt.timedelta(minutes=30)\\n\"")
code.append("        \"            logger.info(\\\"[SELL] 익절쿨다운 %s 30min\\\", market)\\n\"")
code.append("        \"\\n\"")
code.append("    )")
code.append("    t5 = \"        # \\u2500\\u2500 LiveGuard \\u2500\\u2500\\u2500\\u2500\\u2500\\u2500\\u2500\\u2500\\u2500\\u2500\\u2500\\u2500\\u2500\\u2500\\u2500\\u2500\\u2500\\u2500\\u2500\\u2500\\u2500\\u2500\\u2500\\u2500\\u2500\\u2500\\u2500\\u2500\\u2500\\u2500\\u2500\\u2500\\u2500\\u2500\\u2500\\u2500\\u2500\\u2500\\u2500\\u2500\\u2500\\u2500\\u2500\\u2500\\u2500\\u2500\\u2500\\u2500\\u2500\\u2500\\u2500\\u2500\\u2500\"")
code.append("    if \"[FX6-5]\" in s5:")
code.append("        results.append(\"SKIP FX6-5: 이미 적용\")")
code.append("    elif t5 in s5:")
code.append("        p5.write_text(s5.replace(t5, cd + t5), encoding=\"utf-8\")")
code.append("        results.append(\"OK   FX6-5: 익절 쿨다운 30min\")")
code.append("    else:")
code.append("        results.append(\"SKIP FX6-5: 위치 없음\")")
code.append("else:")
code.append("    results.append(\"SKIP FX6-5: 파일 없음\")")
code.append("")
code.append("print(chr(10).join(results))")
code.append("print(chr(10) + \"--- 컴파일 검증 ---\")")
code.append("for f in [\"strategies/v2/order_block_v2.py\", \"models/rl/ppo_agent.py\", \"core/engine_sell.py\"]:")
code.append("    if Path(f).exists():")
code.append("        try:")
code.append("            py_compile.compile(f, doraise=True)")
code.append("            print(\"OK   \" + f)")
code.append("        except Exception as e:")
code.append("            print(\"FAIL \" + f + \": \" + str(e))")
code.append("    else:")
code.append("        print(\"SKIP \" + f)")
code.append("print(\"백업:\", ARCHIVE)")

Path("fix6.py").write_text(chr(10).join(code), encoding="utf-8")
print("fix6.py 생성 완료")

