Set-Content -Path make_fix6b.py -Encoding utf8 -Value '
from pathlib import Path

code = []
code.append("from pathlib import Path")
code.append("import py_compile, shutil")
code.append("from datetime import datetime")
code.append("")
code.append("ARCHIVE = Path(\"archive/fx6b_\" + datetime.now().strftime(\"%Y%m%d_%H%M%S\"))")
code.append("ARCHIVE.mkdir(parents=True, exist_ok=True)")
code.append("p = Path(\"core/engine_sell.py\")")
code.append("shutil.copy2(p, ARCHIVE / \"engine_sell.py\")")
code.append("s = p.read_text(encoding=\"utf-8\")")
code.append("lines = s.splitlines(keepends=True)")
code.append("")
code.append("idx_a = 555")
code.append("if \"profit_rate\" in lines[idx_a] and \"FX6-3\" not in lines[idx_a]:")
code.append("    lines[idx_a] = lines[idx_a].replace(")
code.append("        '\"profit_rate\": profit_rate,',")
code.append("        '\"profit_rate\": profit_rate / 100.0,  # [FX6-3],'")
code.append("    )")
code.append("    print(\"OK   FX6-3 partial 556줄\")")
code.append("else:")
code.append("    print(\"SKIP FX6-3 partial:\", repr(lines[idx_a].strip()))")
code.append("")
code.append("idx_b = 1197")
code.append("if \"profit_rate\" in lines[idx_b] and \"FX6-3\" not in lines[idx_b]:")
code.append("    lines[idx_b] = lines[idx_b].replace(")
code.append("        '\"profit_rate\": profit_rate,',")
code.append("        '\"profit_rate\": profit_rate / 100.0,  # [FX6-3],'")
code.append("    )")
code.append("    print(\"OK   FX6-3 sell 1198줄\")")
code.append("else:")
code.append("    print(\"SKIP FX6-3 sell:\", repr(lines[idx_b].strip()))")
code.append("")
code.append("idx_c = 1428")
code.append("if \"LiveGuard\" in lines[idx_c] and \"[FX6-5]\" not in s:")
code.append("    cd = (")
code.append("        \"\\n\"")
code.append("        \"        # [FX6-5] 익절 후 30분 재진입 쿨다운\\n\"")
code.append("        \"        if profit_rate > 0 and not _is_sl:\\n\"")
code.append("        \"            if not hasattr(self, \\\"_sl_cooldown\\\"):\\n\"")
code.append("        \"                self._sl_cooldown = {}\\n\"")
code.append("        \"            self._sl_cooldown[market] = _dt.datetime.now() + _dt.timedelta(minutes=30)\\n\"")
code.append("        \"            logger.info(\\\"[SELL] 익절쿨다운 %s 30min\\\", market)\\n\"")
code.append("        \"\\n\"")
code.append("    )")
code.append("    lines.insert(idx_c, cd)")
code.append("    print(\"OK   FX6-5 익절 쿨다운 30min\")")
code.append("elif \"[FX6-5]\" in s:")
code.append("    print(\"SKIP FX6-5: 이미 적용\")")
code.append("else:")
code.append("    print(\"SKIP FX6-5:\", repr(lines[idx_c].strip()))")
code.append("")
code.append("p.write_text(\"\".join(lines), encoding=\"utf-8\")")
code.append("")
code.append("try:")
code.append("    py_compile.compile(\"core/engine_sell.py\", doraise=True)")
code.append("    print(\"컴파일 OK\")")
code.append("except Exception as e:")
code.append("    print(\"컴파일 FAIL:\", e)")
code.append("print(\"백업:\", ARCHIVE)")

Path("fix6b.py").write_text(chr(10).join(code), encoding="utf-8")
print("fix6b.py 생성 완료")
'
