import pathlib

lines = []
lines.append("# APEX BOT 일일 운영 리포트 - 2026-04-20")
lines.append("")
lines.append("## 1. 오늘 완료된 코드 수정 (커밋별)")
lines.append("")
lines.append("### [d80d247] fix: 장기보유 강제청산 및 긴급손절 조건 수정")
lines.append("- engine_cycle.py: 긴급손절 조건에 12h+ 보유시 confidence 완화")
lines.append("  - 기존: pnl_pct <= -2.5 and confidence >= 0.50")
lines.append("  - 변경: pnl_pct <= -2.5 and (confidence >= 0.50 or _held_min >= 720)")
lines.append("- engine_schedule.py: _time_based_tp_threshold 반환값 수정")
lines.append("  - 48h 이상: -999.0 (강제청산, 손실도 감수)")
lines.append("  - 24~48h: 0.5% (기존 0.3%에서 상향)")
lines.append("  - 6~24h: 0.8% (유지)")
lines.append("  - 0~6h: 1.5% (유지)")
lines.append("- 2 files changed, 68 insertions, 66 deletions")
lines.append("")
lines.append("### [35ac7d3] feat: apex_daily.py 전략별/시간대별 분석 추가")
lines.append("- 전략별 성과, 시간대별 성과, MDD, 연속손실 섹션 추가")
lines.append("- 152 insertions, 42 deletions")
lines.append("")
lines.append("### [b5c22c9] fix: apex_daily.py profit_rate 단위 버그 수정")
lines.append("- profit_rate가 % 단위로 저장됨을 반영 (100 곱하기 중복 제거)")
lines.append("- 수익팩터 0.993(오류) -> 2.622(정상)으로 정정")
lines.append("- 88 insertions, 157 deletions")
lines.append("")
lines.append("### [미커밋] fix: ATR 손절가 -3% cap 적용 (수정 필요)")
lines.append("- 목표: _check_position_exits에서 basic_sl에 -3% cap 추가")
lines.append("  - basic_sl = max(_sl_levels.stop_loss, entry_price * 0.97)")
lines.append("- 상태: 대상 줄 미발견으로 미적용 -> 별도 확인 필요")
lines.append("- 배경: SUPER 종목 ATR 기반 -4.8% 손절 발생 (cap 미적용 확인)")
lines.append("")
lines.append("---")
lines.append("")
lines.append("## 2. 현재 핵심 성능 지표 (2026-04-20 최종)")
lines.append("")
lines.append("| 지표 | 값 | 목표 | 상태 |")
lines.append("|------|-----|------|------|")
lines.append("| 총 거래 수(매도) | 105건 | - | - |")
lines.append("| 승률 | 66.7% (70승/35패) | 65%+ | OK |")
lines.append("| 평균 수익 | +1.747% | - | OK |")
lines.append("| 평균 손실 | -1.537% | - | OK |")
lines.append("| 수익 팩터 | 2.273 | 2.0+ | OK |")
lines.append("| 누적 수익 | +26,845원 | - | OK |")
lines.append("| 최대 낙폭(MDD) | 27.83% (9,447원) | 15% 이하 | NG |")
lines.append("| 연속 손실 | 1회 | - | OK |")
lines.append("")
lines.append("---")
lines.append("")
lines.append("## 3. 전략별 성과 요약")
lines.append("")
lines.append("| 전략 | 거래수 | 승률 | 평균수익 | 순손익 | 상태 |")
lines.append("|------|--------|------|----------|--------|------|")
lines.append("| Order_Block | 37 | 78% | +1.071% | +23,456원 | OK |")
lines.append("| BEAR_REVERSAL | 9 | 100% | +0.972% | +1,602원 | OK |")
lines.append("| Bollinger_Squeeze | 5 | 100% | +2.315% | +3,773원 | OK |")
lines.append("| RSI_Divergence | 4 | 75% | +0.657% | +812원 | OK |")
lines.append("| VWAP_Reversion | 11 | 55% | +0.461% | +1,279원 | NG |")
lines.append("| MACD_Cross | 11 | 55% | +0.325% | +188원 | NG |")
lines.append("| Vol_Breakout | 11 | 36% | -0.199% | -4,955원 | NG |")
lines.append("| VWAP+Order_Block | 6 | 33% | -0.347% | -1,104원 | NG |")
lines.append("| ML_Ensemble | 2 | 0% | -1.024% | -1,470원 | NG |")
lines.append("| MACD+Vol_Breakout | 2 | 100% | +0.732% | +1,264원 | OK |")
lines.append("")
lines.append("---")
lines.append("")
lines.append("## 4. 시간대별 성과")
lines.append("")
lines.append("| 시간대 | 거래수 | 승률 | 평균수익 | 상태 |")
lines.append("|--------|--------|------|----------|------|")
lines.append("| 00-06시 | 30 | 67% | +0.683% | OK |")
lines.append("| 06-12시 | 19 | 63% | +0.752% | NG |")
lines.append("| 12-18시 | 18 | 61% | +0.177% | NG |")
lines.append("| 18-24시 | 38 | 71% | +0.802% | OK |")
lines.append("")
lines.append("---")
lines.append("")
lines.append("## 5. 일봉 성과 (날짜별)")
lines.append("")
lines.append("| 날짜 | 거래수 | 승률 | 순손익 | 상태 |")
lines.append("|------|--------|------|--------|------|")
lines.append("| 2026-04-14 | 0 | 0% | 0원 | - |")
lines.append("| 2026-04-15 | 16 | 94% | +11,783원 | OK |")
lines.append("| 2026-04-16 | 27 | 67% | +4,999원 | OK |")
lines.append("| 2026-04-17 | 17 | 82% | +9,778원 | OK |")
lines.append("| 2026-04-18 | 21 | 52% | +1,559원 | NG |")
lines.append("| 2026-04-19 | 2 | 0% | -3,171원 | NG |")
lines.append("| 2026-04-20 | 22 | 55% | +1,898원 | NG |")
lines.append("")
lines.append("오늘(04-20) 최종: 22건, 승률 55%, +1,898원")
lines.append("- Vol_Breakout 집중 손실 발생 (-4,955원 누적)")
lines.append("- ATR cap 버그 확인, 수정 시도했으나 미적용 상태")
lines.append("")
lines.append("---")
lines.append("")
lines.append("## 6. 주요 발견 및 해결된 이슈")
lines.append("")
lines.append("### 해결 완료")
lines.append("1. AQT 59시간 보유 미청산 문제")
lines.append("   - 원인: _check_time_based_exits 48h 조건이 횡보(-1%~+1%)에만 작동")
lines.append("   - 해결: _time_based_tp_threshold에서 48h+ 시 -999.0 반환 (강제청산)")
lines.append("   - 현재: B+C 이중 안전망으로 48h 초과 포지션 반드시 청산됨")
lines.append("")
lines.append("2. profit_rate 단위 버그")
lines.append("   - 원인: apex_daily.py에서 % 단위 값에 100 중복 곱산")
lines.append("   - 해결: 직접 % 단위로 사용하도록 수정")
lines.append("   - 영향: 수익팩터 0.993 -> 2.622 정상화")
lines.append("")
lines.append("### 현재 미해결 이슈")
lines.append("1. ATR -3% cap 미적용")
lines.append("   - SUPER -4.8% 손절 사건 원인 확인됨")
lines.append("   - engine_cycle.py 수정 시도했으나 대상 줄 미발견으로 미적용")
lines.append("   - 내일 재확인 필요")
lines.append("")
lines.append("2. MDD 27.83% (목표 15% 초과)")
lines.append("   - 04-18~19 연속 손절 영향, 현재 회복 추세")
lines.append("")
lines.append("3. Vol_Breakout 승률 36%")
lines.append("   - 11건 중 7건 손절, 주요 손실 주도")
lines.append("   - 데이터 부족(11건)으로 구조적 문제 판단 보류")
lines.append("")
lines.append("4. ML_Ensemble 승률 0%")
lines.append("   - 2건 전패, 데이터 부족으로 판단 보류")
lines.append("")
lines.append("---")
lines.append("")
lines.append("## 7. 청산 로직 구조 (검증 완료)")
lines.append("")
lines.append("실행 순서: _check_time_based_exits -> _check_position_exits -> _analyze_existing_position")
lines.append("")
lines.append("A. _check_time_based_exits (line 289)")
lines.append("   - 72h 초과: 무조건 강제청산")
lines.append("   - 48h + 횡보(-1%~+1%): 청산")
lines.append("   - 24h + 손실: 청산")
lines.append("")
lines.append("B. _time_based_tp_threshold (engine_schedule.py)")
lines.append("   - 48h 이상: -999.0 반환 (pnl >= -999 항상 참 -> 강제청산)")
lines.append("   - 24~48h: 0.5% / 6~24h: 0.8% / 0~6h: 1.5%")
lines.append("")
lines.append("C. _analyze_existing_position (line 593)")
lines.append("   - pnl_pct >= _time_based_tp_threshold(market) 조건으로 B와 연동")
lines.append("")
lines.append("A는 독립 백업, B+C가 메인 48h 강제청산 담당")
lines.append("")
lines.append("---")
lines.append("")
lines.append("## 8. 테스트 결과")
lines.append("")
lines.append("| 테스트 | 결과 |")
lines.append("|--------|------|")
lines.append("| test_signal_diagnosis | 1000/1000 통과, S급 (100/100) |")
lines.append("| test_cost_stress | 500/500 통과, 종합평가 OK |")
lines.append("| test_monte_carlo_v2 | 8/8 기준 충족, S급 (100/100) |")
lines.append("| test_independent_verification | 5/5 통과 (98.8%) |")
lines.append("")
lines.append("---")
lines.append("")
lines.append("## 9. 내일 체크포인트 (2026-04-21)")
lines.append("")
lines.append("매일 아침 실행: python apex_daily.py")
lines.append("")
lines.append("### 전략별 모니터링 포인트")
lines.append("")
lines.append("| 전략 | 현재 승률 | 기준 | 액션 |")
lines.append("|------|-----------|------|------|")
lines.append("| Vol_Breakout | 36% | 40% 미만 지속 | 가중치 축소 검토 |")
lines.append("| MACD_Cross | 55% | 65% 미만 지속 | 단독 신호 차단 검토 |")
lines.append("| ML_Ensemble | 0% | 10건 이상 후 | 재평가 |")
lines.append("| Order_Block | 78% | 70% 이하 하락 | 원인 분석 |")
lines.append("")
lines.append("### 04-25 체크포인트")
lines.append("- 총 거래 130건 이상 달성 여부")
lines.append("- Vol_Breakout 승률 개선 여부 (현재 36%)")
lines.append("- MACD_Cross 단독 승률 65% 이상 여부")
lines.append("- MDD 회복 추세 확인")
lines.append("- ATR -3% cap 수정 완료 여부 재확인")
lines.append("")
lines.append("### 05-18 체크포인트 (30일 리뷰)")
lines.append("- 총 거래 200건 이상")
lines.append("- 전략별 구조적 문제 여부 최종 판단")
lines.append("- 급등 포착 실패 빈도 분석 후 스캔 간격 조정 여부 결정")
lines.append("")
lines.append("---")
lines.append("")
lines.append("## 10. 변경하지 않은 항목 (의도적 유지)")
lines.append("")
lines.append("- 스캔 간격 180초 (변경 시 API 429 위험)")
lines.append("- max_dynamic_coins 5개 (변경 시 전략 충돌 위험)")
lines.append("- MACD_Cross 로직 (데이터 부족, 11건으로 판단 불가)")
lines.append("- Vol_Breakout 로직 (데이터 부족, 11건으로 판단 불가)")
lines.append("- 급등 감지 임계값 (데이터 부족으로 구조적 문제 판단 불가)")
lines.append("")
lines.append("---")
lines.append("")
lines.append("## 11. Git 커밋 이력 (2026-04-20)")
lines.append("")
lines.append("| 해시 | 메시지 | 파일 |")
lines.append("|------|--------|------|")
lines.append("| d80d247 | fix: 장기보유 강제청산 및 긴급손절 조건 수정 | engine_cycle.py, engine_schedule.py |")
lines.append("| 35ac7d3 | feat: apex_daily.py 전략별/시간대별 분석 추가 | apex_daily.py |")
lines.append("| b5c22c9 | fix: apex_daily.py profit_rate 단위 버그 수정 | apex_daily.py |")
lines.append("| 미커밋 | fix: ATR 손절가 -3% cap 적용 (미적용 상태) | engine_cycle.py |")
lines.append("")
lines.append("---")
lines.append("")
lines.append("생성일시: 2026-04-20")
lines.append("APEX BOT v3.0 | Mixin Pattern | Python 3.12")

output_path = pathlib.Path("reports/daily_report_2026_04_20.md")
output_path.parent.mkdir(parents=True, exist_ok=True)
output_path.write_text("\n".join(lines), encoding="utf-8")
print(f"리포트 저장 완료: {output_path.resolve()}")
